name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: debian-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@master
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@master

    - name: Get dependencies
      run: |
        go mod download 

    - name: UnitTest
      run: make test
 
    - name: Build
      run: make build
